# -*- coding: utf-8 -*-
"""Performing Active Contour from importing skimage segmentation on Astronaut!

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TVazBXgKMkn3Ggk6zN3ogM41oZmynKd-
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage import data, color
from skimage.filters import gaussian
from skimage.segmentation import active_contour
from skimage.color import rgb2gray
from skimage import data


# Load an image (you can replace this with your own image)
image = data.astronaut()
image_gray = color.rgb2gray(image)


# Plot original image and edge image
fig, ax = plt.subplots(1, 2, figsize=(10, 5))
ax[0].imshow(image, cmap='gray')
ax[0].set_title('Original Image')
ax[1].imshow(image_gray, cmap='gray')
ax[1].set_title('Gray Image')
plt.show()





img = data.astronaut()
img = rgb2gray(img)
# Set up an initial contour (a circle, in this case)
s = np.linspace(0, 2 * np.pi, 400)
r = 100 + 100 * np.sin(s)
c = 220 + 100 * np.cos(s)
init = np.array([r, c]).T

snake = active_contour(
    gaussian(img, sigma=3, preserve_range=False),
    init,
    alpha=0.015,
    beta=10,
    gamma=0.001,
)

fig, ax = plt.subplots(figsize=(7, 7))
ax.imshow(img, cmap=plt.cm.gray)
ax.plot(init[:, 1], init[:, 0], '--r', lw=3)
ax.plot(snake[:, 1], snake[:, 0], '-b', lw=3)
ax.set_xticks([]), ax.set_yticks([])
ax.axis([0, img.shape[1], img.shape[0], 0])

plt.show()